const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1B5E20",
    background: "#FAFAF7",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1B5E20",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5E9",
    secondaryForeground: "#1B5E20",
    muted: "#F4F1EA",
    mutedForeground: "#6B6B6B",
    accent: "#C9A84C",
    accentForeground: "#FFFFFF",
    destructive: "#C62828",
    destructiveForeground: "#FFFFFF",
    border: "#E0D9CF",
    input: "#E0D9CF",
    gold: "#C9A84C",
    goldLight: "#FFF8E1",
  },
  dark: {
    text: "#F0EDE6",
    tint: "#66BB6A",
    background: "#0D1B0F",
    foreground: "#F0EDE6",
    card: "#152419",
    cardForeground: "#F0EDE6",
    primary: "#4CAF50",
    primaryForeground: "#0D1B0F",
    secondary: "#1B3320",
    secondaryForeground: "#A5D6A7",
    muted: "#1A2E1C",
    mutedForeground: "#9E9E9E",
    accent: "#D4AF37",
    accentForeground: "#0D1B0F",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#2E4A33",
    input: "#2E4A33",
    gold: "#D4AF37",
    goldLight: "#1C1A00",
  },
  radius: 16,
};

export default colors;
